import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { File, Paths } from 'expo-file-system';
import { API_URL, analyzeAsset, demoLogin, getDashboard, getIncident, getIncidents, setApiToken, shareIncidentReport } from './src/api';

const C={bg:'#07090D',card:'#11151C',border:'#263142',text:'#F6F8FB',muted:'#8C98A8',accent:'#8C63FF',good:'#46D7A4',warn:'#FFBF5A',bad:'#FF5F6D'};
const DEMO=`2026-09-06T00:31:02Z ERROR sshd Failed password for invalid user admin from 185.220.101.45 port 54112\n2026-09-06T00:31:03Z ERROR sshd Failed password for root from 185.220.101.45 port 54113\n2026-09-06T00:31:04Z WARN authentication anomaly: 22 failed attempts in 60 seconds from 185.220.101.45\n2026-09-06T00:31:05Z CRITICAL privilege escalation attempt detected user=svc-api source=185.220.101.45`;

function Btn({label,onPress,disabled,secondary}){return <Pressable disabled={disabled} onPress={onPress} style={[s.btn,secondary&&s.btn2,disabled&&{opacity:.45}]}><Text style={s.btnText}>{label}</Text></Pressable>}
function Pill({level='LOW'}){const color=level==='CRITICAL'?C.bad:level==='HIGH'?C.bad:level==='MEDIUM'?C.warn:C.good;return <View style={[s.pill,{borderColor:color}]}><Text style={{color,fontSize:9,fontWeight:'900'}}>{level}</Text></View>}
function Header({title,sub,onBack}){return <View style={{flexDirection:'row',gap:10}}>{onBack?<Pressable onPress={onBack} style={s.back}><Text style={s.backT}>‹</Text></Pressable>:null}<View style={{flex:1}}><Text style={s.eye}>SHAKTII // DEFENSE CONSOLE</Text><Text style={s.h1}>{title}</Text>{sub?<Text style={s.sub}>{sub}</Text>:null}</View></View>}
function Card({children,accent}){return <View style={[s.card,accent&&{borderColor:'#44336F',backgroundColor:'#141020'}]}>{children}</View>}

function Login({onLogin}){const[e,setE]=useState('demo@shaktii.ai');const[p,setP]=useState('SHAKTII2026');const[busy,setBusy]=useState(false);return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.login}><Text style={s.eye}>HACKATHON DEMO</Text><Text style={s.logo}>SHAKTII</Text><Text style={s.sub}>Real packet-capture analysis through an Expo client and Node.js API.</Text><Card accent><Text style={s.label}>EMAIL</Text><TextInput style={s.input} value={e} onChangeText={setE} autoCapitalize="none"/><Text style={[s.label,{marginTop:12}]}>PASSWORD</Text><TextInput style={s.input} value={p} onChangeText={setP} secureTextEntry/><Btn disabled={busy} label={busy?'AUTHENTICATING…':'ENTER CONSOLE'} onPress={async()=>{setBusy(true);try{await onLogin(e,p)}catch(err){Alert.alert('Login failed',err.message)}finally{setBusy(false)}}}/><Text style={s.endpoint}>{API_URL}</Text></Card></ScrollView></SafeAreaView>}

function Dashboard({data,onUpload,onHistory,onRefresh,onLogout}){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Header title="Security Command" sub="Live mobile view of the Node analysis session."/><View style={s.stats}><Stat n={data?.totalAnalyses||0} l="Analyses"/><Stat n={data?.critical||0} l="Critical" bad/><Stat n={data?.suspicious||0} l="Suspicious"/><Stat n={`${data?.averageRisk||0}%`} l="Avg Risk"/></View><Card accent><Text style={s.tag}>PRIMARY DEMO ACTION</Text><Text style={s.title}>Analyze a PCAP / PCAPNG</Text><Text style={s.body}>Upload a real capture. The Node engine parses packets, detects attack patterns, scores risk, and returns evidence.</Text><Btn label="UPLOAD & ANALYZE" onPress={onUpload}/></Card><Card><Text style={s.title2}>Recent incidents</Text>{(data?.latest||[]).length?(data.latest.map(x=><View key={x.id} style={s.row}><View style={{flex:1}}><Text style={s.rowT}>{x.fileName}</Text><Text style={s.meta}>{x.id} · Risk {x.riskScore}/100</Text></View><Pill level={x.threatLevel}/></View>)):<Text style={s.body}>No incidents yet.</Text>}<Btn secondary label="OPEN HISTORY" onPress={onHistory}/><Btn secondary label="REFRESH" onPress={onRefresh}/></Card><Pressable onPress={onLogout}><Text style={s.logout}>LOG OUT</Text></Pressable></ScrollView></SafeAreaView>}
function Stat({n,l,bad}){return <View style={s.stat}><Text style={[s.statN,bad&&{color:C.bad}]}>{n}</Text><Text style={s.meta}>{l.toUpperCase()}</Text></View>}

function Upload({onBack,onDone}){const[a,setA]=useState(null);const[busy,setBusy]=useState(false);async function pick(){const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,type:'*/*'});if(r.canceled)return;const x=r.assets[0];if(!['.pcap','.pcapng','.log','.txt','.json','.csv'].some(e=>(x.name||'').toLowerCase().endsWith(e)))return Alert.alert('Unsupported file','Use .pcap, .pcapng, .log, .txt, .json or .csv');setA(x)}function demo(){const f=new File(Paths.cache,'shaktii-demo-attack.log');f.write(DEMO);setA({uri:f.uri,name:'shaktii-demo-attack.log',size:DEMO.length})}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Header title="Capture Ingestion" sub="Select → upload → analyze → report" onBack={onBack}/><Card accent><Text style={s.tag}>SUPPORTED INPUT</Text><Text style={s.title}>PCAP · PCAPNG · LOG · TXT · JSON · CSV</Text><Text style={s.body}>Packet capture parsing happens on the Node.js server. The mobile app only sends the file and renders the returned evidence.</Text><Btn secondary label="CHOOSE FILE" onPress={pick}/><Btn secondary label="LOAD DEMO ATTACK LOG" onPress={demo}/>{a?<View style={s.selected}><Text style={s.rowT}>{a.name}</Text><Text style={s.meta}>{a.size?`${Math.max(1,Math.round(a.size/1024))} KB`:'Ready'}</Text></View>:null}<Btn disabled={!a||busy} label={busy?'UPLOADING / ANALYZING…':'INITIALIZE ANALYSIS'} onPress={async()=>{setBusy(true);try{const r=await analyzeAsset(a);onDone(r.incident)}catch(err){Alert.alert('Analysis failed',err.message)}finally{setBusy(false)}}}/>{busy?<ActivityIndicator color={C.accent} style={{marginTop:14}}/>:null}</Card></ScrollView></SafeAreaView>}

function Result({incident,onBack,onHome}){const[busy,setBusy]=useState(false);const m=incident.metadata||{},a=incident.analytics||{};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Header title="Threat Analysis" sub={`${incident.id} · ${incident.fileName}`} onBack={onBack}/><Card accent><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={s.tag}>RISK SCORE</Text><Text style={s.risk}>{m.overallRiskScore||0}<Text style={s.riskSmall}> / 100</Text></Text></View><Pill level={m.threatLevel}/></View><Text style={s.body}>{incident.executiveSummary}</Text><Text style={s.endpoint}>ENGINE: {incident.aiProvider}</Text></Card><Card><Text style={s.title2}>Detected evidence</Text>{(incident.findings||[]).slice(0,8).map((f,i)=><View key={i} style={s.find}><View style={{flexDirection:'row',gap:8,alignItems:'center'}}><Text style={[s.rowT,{flex:1}]}>{f.eventType}</Text><Pill level={f.severity==='Critical'?'CRITICAL':f.severity==='High'?'HIGH':'MEDIUM'}/></View><Text style={s.body}>{f.description}</Text><Text style={s.meta}>SRC {f.sourceIP} → DST {f.destinationIP} · {f.mitreTag||'N/A'}</Text></View>)}</Card><BarCard title="Protocol distribution" items={a.protocols}/><BarCard title="Top source IPs" items={a.topSourceIPs}/><BarCard title="Top destination ports" items={a.topPorts}/><Card><Text style={s.title2}>Recommended response</Text>{(incident.remediationChecklist||[]).map((x,i)=><Text key={x} style={s.body}>{i+1}. {x}</Text>)}</Card><Card accent><Text style={s.title}>Forensic PDF report</Text><Text style={s.body}>Generated by the Node backend from this incident evidence, then downloaded/shared by Expo.</Text><Btn disabled={busy} label={busy?'GENERATING PDF…':'GENERATE & SHARE PDF'} onPress={async()=>{setBusy(true);try{await shareIncidentReport(incident.id)}catch(err){Alert.alert('Report failed',err.message)}finally{setBusy(false)}}}/><Btn secondary label="RETURN TO DASHBOARD" onPress={onHome}/></Card></ScrollView></SafeAreaView>}
function BarCard({title,items=[]}){const max=Math.max(1,...items.map(x=>Number(x.value||0)));return <Card><Text style={s.title2}>{title}</Text>{items.length?items.slice(0,6).map((x,i)=><View key={i} style={{marginBottom:10}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={s.meta}>{x.label}</Text><Text style={s.meta}>{x.value}</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.max(4,Number(x.value||0)/max*100)}%`}]}/></View></View>):<Text style={s.body}>No data.</Text>}</Card>}

function History({onBack,onOpen}){const[items,setItems]=useState([]);const[busy,setBusy]=useState(true);useEffect(()=>{getIncidents().then(r=>setItems(r.incidents||[])).catch(e=>Alert.alert('History failed',e.message)).finally(()=>setBusy(false))},[]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Header title="Incident History" sub="Current Node server session" onBack={onBack}/>{busy?<ActivityIndicator color={C.accent}/>:items.map(x=><Pressable key={x.id} onPress={()=>onOpen(x.id)} style={s.history}><View style={{flex:1}}><Text style={s.rowT}>{x.fileName}</Text><Text style={s.meta}>{x.id}</Text></View><Pill level={x.metadata?.threatLevel}/></Pressable>)}</ScrollView></SafeAreaView>}

export default function App(){const[screen,setScreen]=useState('login');const[dash,setDash]=useState(null);const[incident,setIncident]=useState(null);async function refresh(){const r=await getDashboard();setDash(r.dashboard)}async function login(e,p){const r=await demoLogin(e,p);setApiToken(r.token);await refresh();setScreen('dash')}if(screen==='login')return <Login onLogin={login}/>;if(screen==='upload')return <Upload onBack={()=>setScreen('dash')} onDone={async x=>{setIncident(x);await refresh();setScreen('result')}}/>;if(screen==='result'&&incident)return <Result incident={incident} onBack={()=>setScreen('upload')} onHome={()=>setScreen('dash')}/>;if(screen==='history')return <History onBack={()=>setScreen('dash')} onOpen={async id=>{const r=await getIncident(id);setIncident(r.incident);setScreen('result')}}/>;return <Dashboard data={dash} onUpload={()=>setScreen('upload')} onHistory={()=>setScreen('history')} onRefresh={()=>refresh().catch(e=>Alert.alert('Refresh failed',e.message))} onLogout={()=>{setApiToken('');setScreen('login')}}/>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},page:{padding:18,paddingBottom:42,gap:15},login:{flexGrow:1,justifyContent:'center',padding:24,gap:14},eye:{fontSize:9,color:'#A78BFA',letterSpacing:1.5,fontWeight:'800'},logo:{fontSize:48,color:C.text,fontWeight:'900',letterSpacing:-2},h1:{fontSize:30,color:C.text,fontWeight:'900',letterSpacing:-1},sub:{fontSize:12,color:C.muted,lineHeight:18,marginTop:4},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:16,padding:17},tag:{fontSize:9,color:'#A78BFA',letterSpacing:1.2,fontWeight:'800',marginBottom:7},title:{fontSize:21,color:C.text,fontWeight:'900'},title2:{fontSize:16,color:C.text,fontWeight:'800',marginBottom:10},body:{fontSize:12,color:C.muted,lineHeight:18,marginTop:8},label:{fontSize:9,color:C.muted,letterSpacing:1.2,fontWeight:'800',marginBottom:6},input:{minHeight:47,borderRadius:11,borderWidth:1,borderColor:C.border,backgroundColor:'#090C11',color:C.text,paddingHorizontal:13},btn:{minHeight:48,borderRadius:11,backgroundColor:C.accent,alignItems:'center',justifyContent:'center',marginTop:13,borderWidth:1,borderColor:C.accent},btn2:{backgroundColor:'transparent',borderColor:C.border},btnText:{fontSize:10,color:'#FFF',fontWeight:'900',letterSpacing:1},endpoint:{fontSize:8,color:'#697586',marginTop:10,textAlign:'center'},back:{width:40,height:40,borderRadius:11,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},backT:{fontSize:30,color:C.text},stats:{flexDirection:'row',flexWrap:'wrap',gap:9},stat:{width:'48.5%',padding:14,borderRadius:13,borderWidth:1,borderColor:C.border,backgroundColor:C.card},statN:{fontSize:26,color:C.text,fontWeight:'900'},meta:{fontSize:9,color:C.muted,marginTop:4},row:{flexDirection:'row',gap:8,alignItems:'center',paddingVertical:11,borderTopWidth:1,borderTopColor:'#202734'},rowT:{fontSize:12,color:C.text,fontWeight:'800'},pill:{borderWidth:1,borderRadius:99,paddingHorizontal:8,paddingVertical:5},logout:{fontSize:9,color:'#6D7889',letterSpacing:1.2,textAlign:'center',padding:12},selected:{marginTop:12,borderWidth:1,borderColor:C.border,borderRadius:11,padding:12,backgroundColor:'#0A0E14'},risk:{fontSize:38,color:C.text,fontWeight:'900'},riskSmall:{fontSize:14,color:C.muted,fontWeight:'600'},find:{paddingTop:11,marginTop:4,borderTopWidth:1,borderTopColor:'#202734'},track:{height:6,backgroundColor:'#252C38',borderRadius:99,overflow:'hidden',marginTop:5},fill:{height:6,backgroundColor:C.accent,borderRadius:99},history:{flexDirection:'row',gap:8,alignItems:'center',padding:14,borderRadius:13,borderWidth:1,borderColor:C.border,backgroundColor:C.card}});
