import PDFDocument from 'pdfkit';

function line(doc, label, value) {
  doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').text(String(value ?? 'N/A'));
}

export function writeIncidentPdf(res, incident) {
  const doc = new PDFDocument({ size: 'A4', margin: 46, info: { Title: `SHAKTII Incident ${incident.id}` } });
  const safeName = String(incident.id || 'incident').replace(/[^a-z0-9_-]/gi, '-');
  res.status(200);
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="SHAKTII-${safeName}.pdf"`);
  doc.pipe(res);

  doc.fontSize(20).font('Helvetica-Bold').text('SHAKTII SECURITY INCIDENT REPORT');
  doc.moveDown(0.3);
  doc.fontSize(9).font('Helvetica').fillColor('#555555').text('Hackathon defensive network analysis report');
  doc.fillColor('#000000').moveDown();

  line(doc, 'Incident ID', incident.id);
  line(doc, 'Created', incident.createdAt);
  line(doc, 'Source file', incident.fileName);
  line(doc, 'Detected type', incident.metadata?.logTypeDetected);
  line(doc, 'Threat level', incident.metadata?.threatLevel);
  line(doc, 'Risk score', `${incident.metadata?.overallRiskScore ?? 0}/100`);
  line(doc, 'Time range', incident.metadata?.timeRangeCovered);
  if (incident.metadata?.packetsAnalyzed) line(doc, 'Packets analyzed', Number(incident.metadata.packetsAnalyzed).toLocaleString());
  line(doc, 'Analysis engine', incident.aiProvider || 'SHAKTII deterministic engine');

  doc.moveDown();
  doc.fontSize(14).font('Helvetica-Bold').text('1. Executive Summary');
  doc.fontSize(10).font('Helvetica').moveDown(0.35).text(incident.executiveSummary || 'Analysis completed.', { lineGap: 3 });

  doc.moveDown();
  doc.fontSize(14).font('Helvetica-Bold').text('2. Severity Breakdown');
  const s = incident.severityBreakdown || {};
  doc.fontSize(10).font('Helvetica').moveDown(0.35)
    .text(`Critical: ${s.critical || 0}    High: ${s.high || 0}    Medium: ${s.medium || 0}    Low: ${s.low || 0}    Info: ${s.info || 0}`);

  doc.moveDown();
  doc.fontSize(14).font('Helvetica-Bold').text('3. Findings');
  const findings = Array.isArray(incident.findings) ? incident.findings.slice(0, 20) : [];
  if (!findings.length) {
    doc.fontSize(10).font('Helvetica').moveDown(0.35).text('No dominant suspicious pattern was identified by the deterministic rules.');
  } else {
    findings.forEach((finding, index) => {
      if (doc.y > 700) doc.addPage();
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica-Bold').text(`${index + 1}. [${finding.severity}] ${finding.eventType}`);
      doc.fontSize(9).font('Helvetica').text(`Source: ${finding.sourceIP || 'Unknown'}   Destination: ${finding.destinationIP || 'Unknown'}   MITRE: ${finding.mitreTag || '-'}`);
      doc.text(finding.description || '', { lineGap: 2 });
    });
  }

  doc.moveDown();
  if (doc.y > 650) doc.addPage();
  doc.fontSize(14).font('Helvetica-Bold').text('4. Indicators of Compromise / Investigation Targets');
  const iocs = Array.isArray(incident.iocs) ? incident.iocs.slice(0, 20) : [];
  if (!iocs.length) doc.fontSize(10).font('Helvetica').moveDown(0.35).text('No high-confidence indicators were extracted.');
  else iocs.forEach((ioc) => doc.fontSize(9).font('Helvetica').text(`• ${ioc.value} — ${ioc.type} — ${ioc.reputation}`));

  doc.moveDown();
  if (doc.y > 650) doc.addPage();
  doc.fontSize(14).font('Helvetica-Bold').text('5. Recommended Actions');
  (incident.remediationChecklist || []).forEach((item, index) => {
    doc.fontSize(10).font('Helvetica').moveDown(0.25).text(`${index + 1}. ${item}`, { lineGap: 2 });
  });

  doc.moveDown();
  doc.fontSize(8).fillColor('#666666').text('Generated by SHAKTII. Findings are decision-support signals and should be validated against authoritative telemetry before containment.', { align: 'center' });
  doc.end();
}
